// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAODVeQKWR3OpoCnCw0RXw8N7rs3x1KWmw',
    appId: '1:151714532695:android:bb1874473e1a02e1288212',
    messagingSenderId: '151714532695',
    projectId: 'fitness-bbe1c',
    storageBucket: 'fitness-bbe1c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuJOS7mJ6Q8XJzGgrZ1za2mqicVfgeZOE',
    appId: '1:151714532695:ios:41e1f5c77801e596288212',
    messagingSenderId: '151714532695',
    projectId: 'fitness-bbe1c',
    storageBucket: 'fitness-bbe1c.firebasestorage.app',
    androidClientId:
        '151714532695-eg5di2n182nenp5dbge8mtek0jum9k0t.apps.googleusercontent.com',
    iosClientId:
        '151714532695-3htf2n1jai6omt04frkcmlfbkdvj979m.apps.googleusercontent.com',
    iosBundleId: 'com.fitness.ios',
  );
}
